name: Build

on:
    push:
      branches:
        - main


jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            substituters = root ${{ github.actor }} https://cache.nixos.org
            sandbox = relaxed
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix build --fallback --system x86_64-linux --option sandbox relaxed .#presentations --json --out-link static
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: static # The folder the action should deploy.